pairs: 
  quote: [BTC]
  base: [EUR]


exchanges: [
  BINANCE,
  FTX,
  BITPANDA,
  BITSTAMP
  ]


BINANCE:
  host: https://api.binance.com/api/v3
  price: 
    endpoint: /ticker/price
    price_data: price
  query: symbol
  pairs_merge: ""
  where_data: null


FTX:
  host: https://ftx.com/api
  price: 
    endpoint: /markets/
    price_data: price
  query: null
  pairs_merge: /
  where_data: result


BITPANDA:
  host: https://api.exchange.bitpanda.com/public/v1
  price:
    endpoint: /price-ticks/
    price_data: price
  query: null
  pairs_merge: _
  where_data: 1


BITSTAMP:
  host: https://www.bitstamp.net/api/v2
  price:
    endpoint: /ticker/
    price_data: last
  query: null
  pairs_merge: ""
  where_data: 2